language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"

# command to install dependencies
install:
  - "pip install coveralls"
  - "python setup.py -q install"

# command to run tests
script:
  coverage run --source=twitter_monitor setup.py -q test

after_success:
  coveralls
